### PR TITLE
Add secure-transport on macOS

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
cc @isuruf I think this works. Needs a bit of a change in micromamba, but I can easily patch that!

**Comment by isuruf** [comment]
Looks good. Can you check that `curl-config --ssl-backends` have both backends in macos?

**Comment by wolfv** [comment]
I just added a test to check that.

**Comment by isuruf** [comment]
Looks good to me. I'm not a maintainer of this feedstock. @conda-forge/curl, thoughts?

**Comment by jakirkham** [comment]
This is a nice improvement. Thank you both! 🙏

**Pull request merged**
