### PR TITLE
Add nghttp2 support for unix systems

### LINKED ISSUE #46: HTTP/2 support
Could this be built against nghttp2? See https://curl.haxx.se/docs/http2.html 

This would then enable HTTP2 support in downstream libraries like e.g. gdal.

### PR DESCRIPTION
**Pull request by cpaulik**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix #46

### CODE REVIEW

**Comment by cpaulik** [comment]
@conda-forge-admin, please rerender

**Comment by cpaulik** [comment]
@conda-forge-admin, please rerender

**Comment by cpaulik** [comment]
It seems openssl is pinned to `1.1.1a` but not for `nghttp2`. Where do we have to change this since it is not in the `meta.yml` directly?

**Comment by wolfv** [comment]
Getting this to work would be great for mamba!

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by wolfv** [comment]
I have added AARCH64 and PPC64LE builds for libev and libnghttp2, let's see if this passes now :)

**Pull request merged**
