### PR TITLE
Update curl

### PR DESCRIPTION
**Pull request by ocefpaf**
I also added the `vc`s here.

### CODE REVIEW

**Comment by ocefpaf** [comment]
`AppVeyor` shows an error that we are missing:

```
libssh2.lib(crypt.c.obj) : error LNK2019: unresolved external symbol _EVP_CIPHER_CTX_cleanup referenced in function _crypt_dtor
..\builds\libcurl-vc9-x86-release-dll-zlib-dll-ssh2-dll-ipv6-sspi-winssl-obj-lib\libcurl.dll : fatal error LNK1120: 68 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\link.exe"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
(C:\bld\curl_1500654882454\_b_env) C:\bld\curl_1500654882454\work\curl-7.54.1\winbuild>if 2 EQU 1 exit 1 
```

**Comment by nehaljwani** [comment]
This is probably failing because the libssh2 package on the channel is a static lib and not a shared lib. We probably need to fix https://github.com/conda-forge/libssh2-feedstock/pull/9 and then build that package, and then trigger this one.

**Comment by ocefpaf** [comment]
> This is probably failing because the libssh2 package on the channel is a static lib and not a shared lib. We probably need to fix https://github.com/conda-forge/libssh2-feedstock/pull/9 and then build that package, and then trigger this one.

Now https://github.com/conda-forge/libssh2-feedstock/pull/11

**Comment by ocefpaf** [comment]
Thanks @nehaljwani for starting this. It seems that `curl` is finally back on track!

**Pull request merged**
