### PR TITLE
remove curl.exe from libcurl

### LINKED ISSUE #78: ClobberWarning: This transaction has incompatible packages due to a shared path
I got a warning on windows, supposedly curl and libcurl have a conflict:
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
2020-08-05T12:08:13.0883381Z   packages: conda-forge/win-64::libcurl-7.71.1-h4b64cdc_4, conda-forge/win-64::curl-7.71.1-h4b64cdc_4
2020-08-05T12:08:13.0884015Z   path: 'library/bin/curl.exe'
```
However the files section of libcurl seems correct and does not list the .exe

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes #78 
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
The clobber warning is indeeded gone:

New: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=202872&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1874

Old: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=198347&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1904

**Review by jschueller — APPROVED** [review]

**Comment by hmaarrfk** [comment]
@conda-forge/curl any thoughts on this before it gets too stale?

**Comment by wolfv** [comment]
looks good to me.

**Comment by hmaarrfk** [comment]
thanks!

**Pull request merged**
