### PR TITLE
Enable websockets in build

### PR DESCRIPTION
**Pull request by jamespinkerton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I'm usually afraid of adding more options to such wide used libraries that tons of other packages link to. With that said:

1. Can you explain why you need this and why we should consider merging?
2. @isuruf, as usually sorry for the ping, but do you foresee any problems or is this one safe to merge?

**Comment by jamespinkerton** [comment]
I get that it’s a valid concern. This flag is needed to use libcurl to interact with ws:// and wss:// connections, which I would like to do. My entire environment uses conda-forge and I can’t easily use libcurl without getting it through conda.

**Comment by ocefpaf** [comment]
> I get that it’s a valid concern. This flag is needed to use libcurl to interact with ws:// and wss:// connections, which I would like to do. My entire environment uses conda-forge and I can’t easily use libcurl without getting it through conda.

If I don't get a comment from an expert in 1-2 days I'll merge this one.

**Comment by jamespinkerton** [comment]
Quick question (I'm sure this is a dumb question). How do we upload this change as a new version in the conda forge channels?

**Comment by ocefpaf** [comment]
> Quick question (I'm sure this is a dumb question). How do we upload this change as a new version in the conda forge channels?

Build number 1 should be in the channel already.

**Comment by jamespinkerton** [comment]
My apologies but I don't see it in the channel?

**Comment by jakirkham** [comment]
The build did not start on Azure. Have [manually started it]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=965076&view=results )

**Pull request merged**
