### PR TITLE
Enable unicode on windows

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Current release doesn't mention `Unicode` in its features:

```
curl -V
curl 7.80.0 (x86_64-pc-win32) libcurl/7.80.0 Schannel zlib/1.2.11 libssh2/1.10.0
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets alt-svc libz
```

... but it does work:

image

**Comment by wolfv** [comment]
Yeah, this is the code path we need to take inside curl: https://github.com/curl/curl/blob/b31d9ccfc2da288900e6857ad8d048c612328cac/lib/curl_multibyte.c#L117-L133

To use the `wfopen` functions and encode the string into wide chars (UTF-16).

**Comment by wolfv** [comment]
I think ENABLE_UNICODE should've worked! Thanks @jaimergp !

**Comment by jaimergp** [comment]
Confirmed: it solved our issues! If anybody else is experiencing unicode problems on Windows, make sure to have `curl 0.18 *_1` or greater

**Pull request merged**
