### PR TITLE
Gcc7

### PR DESCRIPTION
**Pull request by ocefpaf**
Same as #35 but without defaults so we can assess what is missing.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@CJ-Wright and @mariusvniekerk this fails, as expected, with the new compilers due to missing packages. I wonder if we should make the default behavior to remove `defaults` during the compiler migration (pun intended :smile:).

**Comment by CJ-Wright** [comment]
Zlib is in a cycle, so I don't know if this will help. Having defaults in to help us bootstrap would be nice since we can then do another round of builds once the cycle is done and remove defaults, allowing us to do a proper self consistent bootstrap.

**Comment by ocefpaf** [comment]
> Having defaults in to help us bootstrap would be nice since we can then do another round of builds once the cycle is done and remove defaults, allowing us to do a proper self consistent bootstrap.

Sounds good. Even though I would like to try that in the first cycle it is probably faster to cycle twice rather than fixing point issues here and there.

**Comment by CJ-Wright** [comment]
Ah yes

**Pull request closed without merging**
