### PR TITLE
add static build for windows

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
we should probably also split the static library for UNIX in the spirit of CFEP 18. I can do this in this PR or in another, as you wish.

Just FYI this is to enable a statically linked micromamba on Windows.

**Comment by mariusvniekerk** [comment]
Doing the split in this PR seems correct

**Comment by wolfv** [comment]
since the static lib has now been removed, I will do this split soon for UNIX.

**Comment by wolfv** [comment]
Ping @xhochy

**Comment by wolfv** [comment]
yes, sorry, i will fix that ASAP.

**Pull request merged**
