### PR TITLE
make curl thread-safe

### PR DESCRIPTION
**Pull request by kuepe-sl**
Solves #19
make thread-safe by compiling with --enable-threaded-resolver
This option is used by current Debian distributions as well.

Without this option (or c-ares support), libcurl can crash when not called from the main-thread.  
see https://stackoverflow.com/a/22957000 and https://www.redhat.com/archives/libvir-list/2012-September/msg01960.html

EDIT: The Travis CI build failed, but I don't think that's caused by the new configuration parameter.
If someone could clear that up, that would be nice.

### CODE REVIEW

**Comment by jakirkham** [comment]
Toggling as some new `curl` dependencies have been added and the version bumped. It would be nice to see if this now works.

**Comment by jakirkham** [comment]
Oops, sorry. Thought I had reopened this before. Will work on getting this in.

**Comment by kuepe-sl** [comment]
Sorry for the lack of response.

I added a workaround (setting CURLOPT_NOSIGNAL to 1) for the issue to my programs shortly after opening the pull request. Thus I didn't get any further crashes regardless of the library being fixed or not.

**Comment by ocefpaf** [comment]
Closing and re-opening to restart the CIs.

**Comment by ocefpaf** [comment]
@kuepe-sl closing this as stale then. If you ever need to implement this again please open a new PR. Thanks!

**Pull request closed without merging**
